services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus-local
    hostname: prometheus
    restart: unless-stopped
    privileged: true
    user: root
    volumes:
      - prometheus-data:/opt/bitnami/prometheus/data
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prometheus-network
volumes:
  prometheus-data:

networks:
  prometheus-network: